[project]
name = 'Blockchain-Enabled-Specialized-Medical-Waste-Disposal'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.waste-generator]
path = 'contracts/waste-generator.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
